name: build

on:
  pull_request:
    branches: [ lab1 ]

  workflow_dispatch:

jobs:

  build-unix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: ./mvnw clean package
        shell: bash

  build-windows:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: mvnw.cmd clean package
        shell: cmd
